DROP TABLE IF EXISTS games CASCADE;

CREATE TABLE games (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  publisher VARCHAR(255) NOT NULL,
  bgg_id INTEGER NOT NULL,
  average_bgg_rating INTEGER NOT NULL,
  image VARCHAR(255) NOT NULL
);
