DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE events (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255),
  image VARCHAR(255),
  spots INTEGER,
  is_open BOOLEAN NOT NULL DEFAULT FALSE,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);