DROP TABLE IF EXISTS attendances CASCADE;

CREATE TABLE attendances (
  id SERIAL PRIMARY KEY NOT NULL,
  is_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  is_invited BOOLEAN NOT NULL DEFAULT TRUE,
  is_not_assisting BOOLEAN NOT NULL DEFAULT FALSE,
  attendant_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE
);