DROP TABLE IF EXISTS plays_users CASCADE;

CREATE TABLE plays_users (
  id SERIAL PRIMARY KEY NOT NULL,
  score INTEGER,
  is_winner BOOLEAN NOT NULL DEFAULT FALSE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  play_id INTEGER REFERENCES plays(id) ON DELETE CASCADE
);