DROP TABLE IF EXISTS friends CASCADE;

CREATE TABLE friends (
  id SERIAL PRIMARY KEY NOT NULL,
  is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
  user1_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  user2_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);