INSERT INTO games (id, name, description, yearpublished, age, playtimemin, playtimemax, bggid, averagebggrating, thumbnail, image, category, mechanic) VALUES
(
        1,
        "Die Macher",
        "Die Macher is a game about seven sequential political races in different regions of Germany. Players are in charge of national political parties, and must manage limited resources to help their party to victory. The winning party will have the most victory points after all the regional elections. There are four different ways of scoring victory points. First, each regional election can supply one to eighty victory points, depending on the size of the region and how well your party does in it. Second, if a party wins a regional election and has some media influence in the region, then the party will receive some media-control victory points. Third, each party has a national party membership which will grow as the game progresses and this will supply a fair number of victory points. Lastly, parties score some victory points if their party platform matches the national opinions at the end of the game.\n\nThe 1986 edition featured four parties from the old West Germany and supported 3-4 players. The 1997 edition supports up to five players in the re-united Germany and updated several features of the rules as well.  The 2006 edition also supports up to five players and adds a shorter five-round variant and additional rules updates by the original designer.\n\n",
        1986,
        14,
        240,
        240,
        1,
        7.6246, 
        "https://cf.geekdo-images.com/thumb/img/Y2pmp3_tPmiyJ032upHBwqD49xM=/fit-in/200x150/pic4718279.jpg",
        "https://cf.geekdo-images.com/original/img/uqlrq_bQJqHpcaN7_7qocV5XfbU=/0x0/pic4718279.jpg",
        "Economic, Negotiation, Political",
        "Area Majority / Influence, Auction/Bidding, Dice Rolling, Hand Management, Simultaneous Action Selection"),
(
        2,
        "Dragonmaster",
        "Dragonmaster is a trick-taking card game based on an older game called Coup d'Ã‰tat. Each player is given a supply of plastic gems, which represent points. Each player will get to be the dealer for five different hands, with slightly different goals for each hand. After all cards have been dealt out, the dealer decides which hand best suits his or her current cards, and the other players are penalized points (in the form of crystals) for taking certain tricks or cards. For instance, if 'first' or 'last' is called, then a player is penalized for taking the first or last tricks. All players will get a chance to be dealer for five hands, but other players can steal this opportunity by taking all of the tricks during certain hands. At the end, the biggest pile of gems wins the game.\n\nJewel contents:\n\n10 clear (2 extra)\n14 green (2 extra)\n22 red (2 extra)\n22 blue (2 extra)\n\n",
        1981,
        12,
        30,
        30,
        2,
        6.60149, 
        "https://cf.geekdo-images.com/thumb/img/2tQqL6whiVTSAxR7iG8F1CMMcFY=/fit-in/200x150/pic4001505.jpg",
        "https://cf.geekdo-images.com/original/img/o07K8ZVh0PkOpOnSZs1TuABb7I4=/0x0/pic4001505.jpg",
        "Card Game, Fantasy",
        "Trick-taking"),
(
        3,
        "Samurai",
        "Part of the Knizia tile-laying trilogy, Samurai is set in medieval Japan. Players compete to gain the favor of three factions: samurai, peasants, and priests, which are represented by helmet, rice paddy, and Buddha figures scattered about the board, which features the islands of Japan. The competition is waged through the use of hexagonal tiles, each of which help curry favor of one of the three factions &mdash; or all three at once! Players can make lightning-quick strikes with horseback ronin and ships or approach their conquests more methodically. As each figure (helmets, rice paddies, and Buddhas) is surrounded, it is awarded to the player who has gained the most favor with the corresponding group.\n\nGameplay continues until all the symbols of one type have been removed from the board or four figures have been removed from play due to a tie for influence.\n\nAt the end of the game, players compare captured symbols of each type, competing for majorities in each of the three types. Ties are not uncommon and are broken based on the number of other, 'non-majority' symbols each player has collected.\n\n",
        1998,
        10,
        30,
        60,
        3,
        7.44068, 
        "https://cf.geekdo-images.com/thumb/img/BOzp5hzTDSHjXf0yijvREDXxQos=/fit-in/200x150/pic3211873.jpg",
        "https://cf.geekdo-images.com/original/img/mPS50ts53753q5-kb5vWbTDN8Z0=/0x0/pic3211873.jpg",
        "Abstract Strategy, Medieval",
        "Area Majority / Influence, Hand Management, Set Collection, Tile Placement"),
(
        4,
        "Tal der Könige",
        "When you see the triangular box and the luxurious, large blocks, you can tell this game was designed to be beautiful as well as functional.  The object of the game is to build pyramids out of the different colored blocks.  A pyramid scores more points when it's made from a few colors, but it's much harder to consistently outbid the other players for the necessary blocks.  The game is over when the Pharoah's Pyramid in the center is completed, which is built using all the blocks that the players don't use during the course of the game.\n\nFinal round 1990 Hippodice Spieleautorenwettbewerb.\n\n",
        1992,
        12,
        60,
        60,
        4,
        6.60804, 
        "https://cf.geekdo-images.com/thumb/img/aqEMohPTNBbRO84X7J5tq3dirBk=/fit-in/200x150/pic285299.jpg",
        "https://cf.geekdo-images.com/original/img/TgcSkyM0Stk6Xz4ZahXrhpVfjm8=/0x0/pic285299.jpg",
        "Ancient",
        "Action Points, Area Majority / Influence, Auction/Bidding, Set Collection"),
(
        5,
        "Acquire",
        "In Acquire, each player strategically invests in businesses, trying to retain a majority of stock.  As the businesses grow with tile placements, they also start merging, giving the majority stockholders of the acquired business sizable bonuses, which can then be used to reinvest into other chains.  All of the investors in the acquired company can then cash in their stocks for current value or trade them 2-for-1 for shares of the newer, larger business.  The game is a race to acquire the greatest wealth.\n\nThis Sid Sackson classic has taken many different forms over the years depending on the publisher.  Some versions of the 3M bookshelf edition included rules for a 2-player variant. The original version is part of the 3M Bookshelf Series.\n\nNote: many books and websites incorrectly list this as a 1962 publication.\n\n",
        1964,
        12,
        90,
        90,
        5,
        7.34843, 
        "https://cf.geekdo-images.com/thumb/img/ZODhu5g13HRQEcOgMP8oiRooQQc=/fit-in/200x150/pic3299296.jpg",
        "https://cf.geekdo-images.com/original/img/Bz4tTHNpq6gUKFkJs0fJdVIGR1s=/0x0/pic3299296.jpg",
        "Economic",
        "Hand Management, Investment, Market, Ownership, Stock Holding, Tile Placement"),
(
        6,
        "Mare Mediterraneum",
        "In the ancient lands along the Mediterranean, players attempt to satisfy their unique victory conditions via trade, war and construction.  This lavishly produced game contains tons of wooden game components and a beautiful roll-out vinyl map.  Players produce a score of different commodities to trade with other cities in the hope of creating enough income to fill their capitals with buildings, produce artwork, and fill warehouses with goods.\n\n",
        1989,
        12,
        240,
        240,
        6,
        6.50443, 
        "https://cf.geekdo-images.com/thumb/img/MPGApu8bmkLesVqWpSZawq2jlLI=/fit-in/200x150/pic28424.jpg",
        "https://cf.geekdo-images.com/original/img/mmk6bqbXRiIKfS5sovP8uA_wSQA=/0x0/pic28424.jpg",
        "Civilization, Nautical",
        "Dice Rolling"),
(
        7,
        "Cathedral",
        "In Cathedral, each player has a set of pieces of a different color. The pieces are in the shapes of buildings, covering from one to five square units. The first player takes the single neutral Cathedral piece and places it onto the board. Players then alternate placing one of their buildings onto the board until neither player can place another building. Players capture territory by surrounding areas that are occupied by at most one opponent or neutral building. A captured piece is removed and captured territory becomes off-limits to the opponent. The player with the fewest 'square units' of buildings that can't be placed wins.\n\n",
        1978,
        8,
        20,
        20,
        7,
        6.51326, 
        "https://cf.geekdo-images.com/thumb/img/_o2Qy_RXfWQs7gaIwwsB3l6oEJU=/fit-in/200x150/pic181642.jpg",
        "https://cf.geekdo-images.com/original/img/Gri8ET3BFLE6mzdQLyWZnjWv25s=/0x0/pic181642.jpg",
        "Abstract Strategy",
        "Enclosure, Pattern Building, Pattern Recognition, Tile Placement"),
(
        8,
        "Lords of Creation",
        "In this interesting offering from Warfrog, players become Gods seeking to dominate a world with their followers.  The first part of the game involves constructing the game board, after which players take turns using cards to determine how many new people should appear and what type of terrain they will inhabit.  All tribes start off as barbarians, but soon the calming effect of civilization settles the marauding bands; although civilized tribes score more, they can no longer attack.  What they can do, though, is civilize other players' followers.  Sure it gives opponents more points, but at least those followers won't come after you!\n\n",
        1993,
        12,
        120,
        120,
        8,
        6.1401, 
        "https://cf.geekdo-images.com/thumb/img/YmAF5-CpAuD1kbnJTIm7Z6r5p-E=/fit-in/200x150/pic374320.jpg",
        "https://cf.geekdo-images.com/original/img/HjECVVaFq1fjMb-dtlIAI6hKRq0=/0x0/pic374320.jpg",
        "Civilization, Fantasy",
        "Modular Board"),
(
        9,
        "El Caballero",
        "Although referred to as a sequel to El Grande, El Caballero shares few aspects with its namesake, being a fun but intense brain-burner in which players explore and attempt to control the lands and waterways of the New World.\n\nThe players are following Columbus by exploring the islands he discovered. Players slowly explore the islands &ndash; by picking and placing land tiles that are most favorable to them &ndash; and discover wealth in the form of gold and fish. As they learn about the land and sea areas of this new land, they position their caballeros to try to maintain control of the important regions. Castillos give them a measure of protection from others, and ships allow them to establish trade and to fish for food. Success is measured in the size of land and sea areas they control. Their success is measured twice, and in the end these scores are summed and the winner declared.\n\n",
        1998,
        13,
        90,
        90,
        9,
        6.47713, 
        "https://cf.geekdo-images.com/thumb/img/vh6QNbi9pJO4rkdMFdeqkDDKPtQ=/fit-in/200x150/pic1731731.jpg",
        "https://cf.geekdo-images.com/original/img/p_RmeyXFl0-NdTUxAAX-U9fkIRY=/0x0/pic1731731.jpg",
        "Exploration",
        "Area Majority / Influence, Tile Placement"),
(
        10,
        "Elfenland",
        "Elfenland is a redesign of the original White Wind game Elfenroads.  The game is set in the mythical world of the elves.  A group of fledgling elves (the players) are charged with visiting as many of the twenty Elfencities as they can over the course of 4 rounds.  To accomplish the task they will use various forms of transportation such as Giant Pigs, Elfcarts, Unicorns, Rafts, Magic Clouds, Trollwagons, and Dragons.\n\nGameplay:  Players begin in the Elf capitol, draw one face down movement tile, and are dealt eight transport cards and a secret 'home' city card that they must reach at the end of the 4th round or lose points for each city space away from 'home' they are at the end of the game. Markers of each player's color are placed in each city on the board and are collected when the player visits that city (each counts as 1 point).\n  \n     The round proceeds in 2 stages.  The first part of the round consists of the drawing of Tiles showing the differing types of transport (except rafts) from a combination of face up and face down tiles (if a player doesn't like the 5 tiles that are face up; they can always draw blind from the face down tiles and hope to get one they need).  These transport tiles need to match the Transportation cards in your hand to use them most effectively.  After each player has a total of 4 tiles they take turns placing a tile on any one of the roads that run between the elf cities.  Only one transport tile may be placed on each road; so players may use other players tiles to travel if they have the matching cards in their hand.  This frequently causes a readjustment of planned travel routes as other players tiles can allow you to move farther or shorter than you had first thought.  Players can play their tiles to help themselves or hinder others by playing a slow mode of transport on another players (perceived) path.\n\nEach mode of transport has certain terrain it can travel through quickly or slowly, and those that it cannot. These are listed on the top of each transportation card by the number terrain symbols.  The number of terrain symbols equals how many matching cards you must play to move across a given tile in a given terrain.  For example, a Magic Cloud tile placed in a mountain would take one Magic cloud card to travel across (1 mountain symbol on card means Magic clouds are fast in mountains). If the same tile was placed on a road in forest terrain it would require 2 Magic Cloud cards to travel that route (2 Forest symbols on card means Magic Clouds are slow in Forest).  Magic Clouds cannot travel in desert terrain at all (no desert symbols on card). All modes of transport are different and Rafts can be used on rivers or lakes without needing tiles. Rafts go slow upstream (2 raft cards needed) and fast downstream (1 card needed).  The small lake requires 1 raft card to travel across and the larger lake requires 2 cards to travel across.  Players may keep one unused transport counter and up to 4 Transportation cards from one round to the next.\n\nThe second part of the round begins after all players have finished placing their transportation tiles for the round.  Each player plays his cards and moves his elf-boot around the board collecting his tokens from the cities visited.  If there is a Transport tile on a route and a player has no matching Transportation card he may 'Caravan' across it by playing any 3 Transportation cards from his hand.\n\nAs a bit of 'take that' each player has a trouble tile which can be placed next to any transportation tile during the first part of the round.  This counter means that in order to travel that path an additional card of the transport type must be played or 4 cards to 'Caravan'.\n\nVictory: if at the end of round 3 a player has visited all 20 cities he is the winner.  If not the game ends after round 4 when 'Home' cities are revealed and each player subtracts points for each city he is away from his 'home' subtracting that from his collected city tokens.  The person with the highest score wins.\n\n",
        1998,
        10,
        60,
        60,
        10,
        6.72701, 
        "https://cf.geekdo-images.com/thumb/img/eqDi6VPAU3XUvDDhqur97X2umO0=/fit-in/200x150/pic1798136.jpg",
        "https://cf.geekdo-images.com/original/img/M3fRcs2sKpffc7Yl1KXodvbBa5Q=/0x0/pic1798136.jpg",
        "Fantasy, Travel",
        "Card Drafting, Hand Management, Network and Route Building, Point to Point Movement");
