INSERT INTO games (id, name, description, year_published, age, play_time_min, play_time_max, bgg_id, average_bgg_rating, thumbnail, image, category, mechanic) VALUES
(
        1,
        'Die Macher',
        'Die Macher is a game about seven sequential political races in different regions of Germany. Players are in charge of national political parties, and must manage limited resources to help their party to victory. The winning party will have the most victory points after all the regional elections. There are four different ways of scoring victory points. First, each regional election can supply one to eighty victory points, depending on the size of the region and how well your party does in it. Second, if a party wins a regional election and has some media influence in the region, then the party will receive some media-control victory points. Third, each party has a national party membership which will grow as the game progresses and this will supply a fair number of victory points. Lastly, parties score some victory points if their party platform matches the national opinions at the end of the game.The 1986 edition featured four parties from the old West Germany and supported 3-4 players. The 1997 edition supports up to five players in the re-united Germany and updated several features of the rules as well.  The 2006 edition also supports up to five players and adds a shorter five-round variant and additional rules updates by the original designer.',
        1986,
        14,
        240,
        240,
        1,
        7.6246, 
        'https://cf.geekdo-images.com/thumb/img/Y2pmp3_tPmiyJ032upHBwqD49xM=/fit-in/200x150/pic4718279.jpg',
        'https://cf.geekdo-images.com/original/img/uqlrq_bQJqHpcaN7_7qocV5XfbU=/0x0/pic4718279.jpg',
        'Economic, Negotiation, Political',
        'Area Majority / Influence, Auction/Bidding, Dice Rolling, Hand Management, Simultaneous Action Selection'),
(
        2,
        'Dragonmaster',
        'Dragonmaster is a trick-taking card game based on an older game called Coup dÃ‰tat. Each player is given a supply of plastic gems, which represent points. Each player will get to be the dealer for five different hands, with slightly different goals for each hand. After all cards have been dealt out, the dealer decides which hand best suits his or her current cards, and the other players are penalized points (in the form of crystals) for taking certain tricks or cards. For instance, if first or last is called, then a player is penalized for taking the first or last tricks. All players will get a chance to be dealer for five hands, but other players can steal this opportunity by taking all of the tricks during certain hands. At the end, the biggest pile of gems wins the game.Jewel contents:10 clear (2 extra)14 green (2 extra)22 red (2 extra)22 blue (2 extra)',
        1981,
        12,
        30,
        30,
        2,
        6.60149, 
        'https://cf.geekdo-images.com/thumb/img/2tQqL6whiVTSAxR7iG8F1CMMcFY=/fit-in/200x150/pic4001505.jpg',
        'https://cf.geekdo-images.com/original/img/o07K8ZVh0PkOpOnSZs1TuABb7I4=/0x0/pic4001505.jpg',
        'Card Game, Fantasy',
        'Trick-taking'),
(
        3,
        'Samurai',
        'Part of the Knizia tile-laying trilogy, Samurai is set in medieval Japan. Players compete to gain the favor of three factions: samurai, peasants, and priests, which are represented by helmet, rice paddy, and Buddha figures scattered about the board, which features the islands of Japan. The competition is waged through the use of hexagonal tiles, each of which help curry favor of one of the three factions &mdash; or all three at once! Players can make lightning-quick strikes with horseback ronin and ships or approach their conquests more methodically. As each figure (helmets, rice paddies, and Buddhas) is surrounded, it is awarded to the player who has gained the most favor with the corresponding group.Gameplay continues until all the symbols of one type have been removed from the board or four figures have been removed from play due to a tie for influence.At the end of the game, players compare captured symbols of each type, competing for majorities in each of the three types. Ties are not uncommon and are broken based on the number of other, non-majority symbols each player has collected.',
        1998,
        10,
        30,
        60,
        3,
        7.44068, 
        'https://cf.geekdo-images.com/thumb/img/BOzp5hzTDSHjXf0yijvREDXxQos=/fit-in/200x150/pic3211873.jpg',
        'https://cf.geekdo-images.com/original/img/mPS50ts53753q5-kb5vWbTDN8Z0=/0x0/pic3211873.jpg',
        'Abstract Strategy, Medieval',
        'Area Majority / Influence, Hand Management, Set Collection, Tile Placement'),
(
        4,
        'Tal der Könige',
        'When you see the triangular box and the luxurious, large blocks, you can tell this game was designed to be beautiful as well as functional.  The object of the game is to build pyramids out of the different colored blocks.  A pyramid scores more points when its made from a few colors, but its much harder to consistently outbid the other players for the necessary blocks.  The game is over when the Pharoahs Pyramid in the center is completed, which is built using all the blocks that the players dont use during the course of the game.Final round 1990 Hippodice Spieleautorenwettbewerb.',
        1992,
        12,
        60,
        60,
        4,
        6.60804, 
        'https://cf.geekdo-images.com/thumb/img/aqEMohPTNBbRO84X7J5tq3dirBk=/fit-in/200x150/pic285299.jpg',
        'https://cf.geekdo-images.com/original/img/TgcSkyM0Stk6Xz4ZahXrhpVfjm8=/0x0/pic285299.jpg',
        'Ancient',
        'Action Points, Area Majority / Influence, Auction/Bidding, Set Collection'),
(
        5,
        'Acquire',
        'In Acquire, each player strategically invests in businesses, trying to retain a majority of stock.  As the businesses grow with tile placements, they also start merging, giving the majority stockholders of the acquired business sizable bonuses, which can then be used to reinvest into other chains.  All of the investors in the acquired company can then cash in their stocks for current value or trade them 2-for-1 for shares of the newer, larger business.  The game is a race to acquire the greatest wealth.This Sid Sackson classic has taken many different forms over the years depending on the publisher.  Some versions of the 3M bookshelf edition included rules for a 2-player variant. The original version is part of the 3M Bookshelf Series.Note: many books and websites incorrectly list this as a 1962 publication.',
        1964,
        12,
        90,
        90,
        5,
        7.34843, 
        'https://cf.geekdo-images.com/thumb/img/ZODhu5g13HRQEcOgMP8oiRooQQc=/fit-in/200x150/pic3299296.jpg',
        'https://cf.geekdo-images.com/original/img/Bz4tTHNpq6gUKFkJs0fJdVIGR1s=/0x0/pic3299296.jpg',
        'Economic',
        'Hand Management, Investment, Market, Ownership, Stock Holding, Tile Placement'),
(
        6,
        'Mare Mediterraneum',
        'In the ancient lands along the Mediterranean, players attempt to satisfy their unique victory conditions via trade, war and construction.  This lavishly produced game contains tons of wooden game components and a beautiful roll-out vinyl map.  Players produce a score of different commodities to trade with other cities in the hope of creating enough income to fill their capitals with buildings, produce artwork, and fill warehouses with goods.',
        1989,
        12,
        240,
        240,
        6,
        6.50443, 
        'https://cf.geekdo-images.com/thumb/img/MPGApu8bmkLesVqWpSZawq2jlLI=/fit-in/200x150/pic28424.jpg',
        'https://cf.geekdo-images.com/original/img/mmk6bqbXRiIKfS5sovP8uA_wSQA=/0x0/pic28424.jpg',
        'Civilization, Nautical',
        'Dice Rolling'),
(
        7,
        'Cathedral',
        'In Cathedral, each player has a set of pieces of a different color. The pieces are in the shapes of buildings, covering from one to five square units. The first player takes the single neutral Cathedral piece and places it onto the board. Players then alternate placing one of their buildings onto the board until neither player can place another building. Players capture territory by surrounding areas that are occupied by at most one opponent or neutral building. A captured piece is removed and captured territory becomes off-limits to the opponent. The player with the fewest square units of buildings that cant be placed wins.',
        1978,
        8,
        20,
        20,
        7,
        6.51326, 
        'https://cf.geekdo-images.com/thumb/img/_o2Qy_RXfWQs7gaIwwsB3l6oEJU=/fit-in/200x150/pic181642.jpg',
        'https://cf.geekdo-images.com/original/img/Gri8ET3BFLE6mzdQLyWZnjWv25s=/0x0/pic181642.jpg',
        'Abstract Strategy',
        'Enclosure, Pattern Building, Pattern Recognition, Tile Placement'),
(
        8,
        'Lords of Creation',
        'In this interesting offering from Warfrog, players become Gods seeking to dominate a world with their followers.  The first part of the game involves constructing the game board, after which players take turns using cards to determine how many new people should appear and what type of terrain they will inhabit.  All tribes start off as barbarians, but soon the calming effect of civilization settles the marauding bands; although civilized tribes score more, they can no longer attack.  What they can do, though, is civilize other players followers.  Sure it gives opponents more points, but at least those followers wont come after you!',
        1993,
        12,
        120,
        120,
        8,
        6.1401, 
        'https://cf.geekdo-images.com/thumb/img/YmAF5-CpAuD1kbnJTIm7Z6r5p-E=/fit-in/200x150/pic374320.jpg',
        'https://cf.geekdo-images.com/original/img/HjECVVaFq1fjMb-dtlIAI6hKRq0=/0x0/pic374320.jpg',
        'Civilization, Fantasy',
        'Modular Board'),
(
        9,
        'El Caballero',
        'Although referred to as a sequel to El Grande, El Caballero shares few aspects with its namesake, being a fun but intense brain-burner in which players explore and attempt to control the lands and waterways of the New World.The players are following Columbus by exploring the islands he discovered. Players slowly explore the islands &ndash; by picking and placing land tiles that are most favorable to them &ndash; and discover wealth in the form of gold and fish. As they learn about the land and sea areas of this new land, they position their caballeros to try to maintain control of the important regions. Castillos give them a measure of protection from others, and ships allow them to establish trade and to fish for food. Success is measured in the size of land and sea areas they control. Their success is measured twice, and in the end these scores are summed and the winner declared.',
        1998,
        13,
        90,
        90,
        9,
        6.47713, 
        'https://cf.geekdo-images.com/thumb/img/vh6QNbi9pJO4rkdMFdeqkDDKPtQ=/fit-in/200x150/pic1731731.jpg',
        'https://cf.geekdo-images.com/original/img/p_RmeyXFl0-NdTUxAAX-U9fkIRY=/0x0/pic1731731.jpg',
        'Exploration',
        'Area Majority / Influence, Tile Placement'),
(
        10,
        'Elfenland',
        'Elfenland is a redesign of the original White Wind game Elfenroads.  The game is set in the mythical world of the elves.  A group of fledgling elves (the players) are charged with visiting as many of the twenty Elfencities as they can over the course of 4 rounds.  To accomplish the task they will use various forms of transportation such as Giant Pigs, Elfcarts, Unicorns, Rafts, Magic Clouds, Trollwagons, and Dragons.Gameplay:  Players begin in the Elf capitol, draw one face down movement tile, and are dealt eight transport cards and a secret home city card that they must reach at the end of the 4th round or lose points for each city space away from home they are at the end of the game. Markers of each players color are placed in each city on the board and are collected when the player visits that city (each counts as 1 point).       The round proceeds in 2 stages.  The first part of the round consists of the drawing of Tiles showing the differing types of transport (except rafts) from a combination of face up and face down tiles (if a player doesnt like the 5 tiles that are face up; they can always draw blind from the face down tiles and hope to get one they need).  These transport tiles need to match the Transportation cards in your hand to use them most effectively.  After each player has a total of 4 tiles they take turns placing a tile on any one of the roads that run between the elf cities.  Only one transport tile may be placed on each road; so players may use other players tiles to travel if they have the matching cards in their hand.  This frequently causes a readjustment of planned travel routes as other players tiles can allow you to move farther or shorter than you had first thought.  Players can play their tiles to help themselves or hinder others by playing a slow mode of transport on another players (perceived) path.Each mode of transport has certain terrain it can travel through quickly or slowly, and those that it cannot. These are listed on the top of each transportation card by the number terrain symbols.  The number of terrain symbols equals how many matching cards you must play to move across a given tile in a given terrain.  For example, a Magic Cloud tile placed in a mountain would take one Magic cloud card to travel across (1 mountain symbol on card means Magic clouds are fast in mountains). If the same tile was placed on a road in forest terrain it would require 2 Magic Cloud cards to travel that route (2 Forest symbols on card means Magic Clouds are slow in Forest).  Magic Clouds cannot travel in desert terrain at all (no desert symbols on card). All modes of transport are different and Rafts can be used on rivers or lakes without needing tiles. Rafts go slow upstream (2 raft cards needed) and fast downstream (1 card needed).  The small lake requires 1 raft card to travel across and the larger lake requires 2 cards to travel across.  Players may keep one unused transport counter and up to 4 Transportation cards from one round to the next.The second part of the round begins after all players have finished placing their transportation tiles for the round.  Each player plays his cards and moves his elf-boot around the board collecting his tokens from the cities visited.  If there is a Transport tile on a route and a player has no matching Transportation card he may Caravan across it by playing any 3 Transportation cards from his hand.As a bit of take that each player has a trouble tile which can be placed next to any transportation tile during the first part of the round.  This counter means that in order to travel that path an additional card of the transport type must be played or 4 cards to Caravan.Victory: if at the end of round 3 a player has visited all 20 cities he is the winner.  If not the game ends after round 4 when Home cities are revealed and each player subtracts points for each city he is away from his home subtracting that from his collected city tokens.  The person with the highest score wins.',
        1998,
        10,
        60,
        60,
        10,
        6.72701, 
        'https://cf.geekdo-images.com/thumb/img/eqDi6VPAU3XUvDDhqur97X2umO0=/fit-in/200x150/pic1798136.jpg',
        'https://cf.geekdo-images.com/original/img/M3fRcs2sKpffc7Yl1KXodvbBa5Q=/0x0/pic1798136.jpg',
        'Fantasy, Travel',
        'Card Drafting, Hand Management, Network and Route Building, Point to Point Movement'),
(
        11,
        'Bohnanza',
        'Bohnanza is the first in the Bohnanza family of games and has been published in several different editions.The cards are colorful depictions of beans in various descriptive poses, and the object is to make coins by planting fields (sets) of these beans and then harvesting them.  To help players match their cards up, the game features extensive trading and deal making.  One of the most unique features of the game is that you cannot rearrange your hand, as you need to play the cards in the order that you draw them.The original German edition supports 3-5 players.The English version from Rio Grande Games comes with the first edition of the first German expansion included in a slightly oversized box.  One difference in the contents, however, is that bean #22s Weinbrandbohne (Brandy Bean) was replaced by the Wachsbohne, or Wax Bean.  This edition includes rules for up to seven players, like the Erweiterungs-Set, but also adapts the two-player rules of Al Cabohne in order to allow two people to play Bohnanza.',
        1997,
        13,
        45,
        45,
        11,
        7.04055, 
        'https://cf.geekdo-images.com/thumb/img/uwI4ME5bA9KTNqmo6fYdUAV8NkE=/fit-in/200x150/pic69366.jpg',
        'https://cf.geekdo-images.com/original/img/Hwyjq4cYfXY2l07Hm9mncHlrI4U=/0x0/pic69366.jpg',
        'Card Game, Farming, Negotiation',
        'Hand Management, Set Collection, Trading'),
(
        12,
        'Ra',
        'Ra is an auction and set-collection game with an Ancient Egyptian theme.  Each turn players are able to purchase lots of tiles with their bidding tiles (suns).  Once a player has used up his or her suns, the other players continue until they do likewise, which may set up a situation with a single uncontested player bidding on tiles before the end of the round occurs.  Tension builds because the round may end before all players have had a chance to win their three lots for the epoch.  The various tiles either give immediate points, prevent negative points for not having certain types at the end of the round (epoch), or give points after the final round.  The game lasts for three epochs (rounds).  The game offers a short learning curve, and experienced players find it both fast-moving and a quick play.From the Box:The game spans 1500 years of Egyptian history in less than an hour!The players seek to expand their power and fame and there are many ways to accomplish this: Influencing Pharaohs, Building monuments, Farming on the Nile, Paying homage to the Gods, Advancing the technology and culture of the people. Ra is an auction and set collecting game where players may choose to take risks for great rewards or... And all this is for the glory of the Sun God Ra!',
        1999,
        12,
        45,
        60,
        12,
        7.46857, 
        'https://cf.geekdo-images.com/thumb/img/6d0zX3j56NknAus56Wf_WqN7S9s=/fit-in/200x150/pic3013552.jpg',
        'https://cf.geekdo-images.com/original/img/iA_LlRmPfFILGon-zvbWeEzxvX8=/0x0/pic3013552.jpg',
        'Ancient, Mythology',
        'Auction/Bidding, Auction: Once Around, Constrained Bidding, Push Your Luck, Set Collection'),
(
        13,
        'Catan',
        'In Catan (formerly The Settlers of Catan), players try to be the dominant force on the island of Catan by building settlements, cities, and roads. On each turn dice are rolled to determine what resources the island produces. Players collect these resources (cards)&mdash;wood, grain, brick, sheep, or stone&mdash;to build up their civilizations to get to 10 victory points and win the game.Setup includes randomly placing large hexagonal tiles (each showing a resource or the desert) in a honeycomb shape and surrounding them with water tiles, some of which contain ports of exchange. Number disks, which will correspond to die rolls (two 6-sided dice are used), are placed on each resource tile. Each player is given two settlements (think: houses) and roads (sticks) which are, in turn, placed on intersections and borders of the resource tiles. Players collect a hand of resource cards based on which hex tiles their last-placed house is adjacent to. A robber pawn is placed on the desert tile.A turn consists of possibly playing a development card, rolling the dice, everyone (perhaps) collecting resource cards based on the roll and position of houses (or upgraded cities&mdash;think: hotels) unless a 7 is rolled, turning in resource cards (if possible and desired) for improvements, trading cards at a port, and trading resource cards with other players. If a 7 is rolled, the active player moves the robber to a new hex tile and steals resource cards from other players who have built structures adjacent to that tile.Points are accumulated by building settlements and cities, having the longest road and the largest army (from some of the development cards), and gathering certain development cards that simply award victory points. When a player has gathered 10 points (some of which may be held in secret), he announces his total and claims the win.Catan has won multiple awards and is one of the most popular games in recent history due to its amazing ability to appeal to experienced gamers as well as those new to the hobby.Die Siedler von Catan was originally published by KOSMOS and has gone through multiple editions. It was licensed by Mayfair and has undergone four editions as The Settlers of Catan. In 2015, it was formally renamed Catan to better represent itself as the core and base game of the Catan series. It has been re-published in two travel editions, portable edition and compact edition, as a special gallery edition (replaced in 2009 with a family edition), as an anniversary wooden edition, as a deluxe 3D collectors edition, in the basic Simply Catan, as a beginner version, and with an entirely new theme in Japan and Asia as Settlers of Catan: Rockman Edition. Numerous spin-offs and expansions have also been made for the game.',
        1995,
        10,
        60,
        120,
        13,
        7.17983, 
        'https://cf.geekdo-images.com/thumb/img/g8LvJsd2oLAub6AEKN_Xpdoi8Sw=/fit-in/200x150/pic2419375.jpg',
        'https://cf.geekdo-images.com/original/img/A-0yDJkve0avEicYQ4HoNO-HkK8=/0x0/pic2419375.jpg',
        'Negotiation',
        'Dice Rolling, Hexagon Grid, Income, Modular Board, Network and Route Building, Race, Random Production, Trading, Variable Setup'),
(
        14,
        'Basari',
        'Basari is a game of gem merchants competing in a marketplace: racing, collecting, trading, and predicting what the other merchants will do.To start the game, players receive 12 gemstones (3 each of 4 colors). Each turn there will be a movement phase and an action phase:For movement, everyone simultaneously rolls their die and moves their markers around a track.They then choose one of three different actions to perform. The actions are:- to take a variety of gems from a market stall, - to immediately score from between 4 and 7 points, or - to roll and move again and also collect points.The action cards are revealed simultaneously. If only 1 player chose a particular action, they simply perform that action. If 2 players chose the same action, they barter back and forth with gemstones. One player will eventually accept the others offer of gems, and the other will take the action. If 3 or 4 players all chose the same action card, that action is cancelled. Note that in 4-player games, there will always be a conflict in choice of 3 actions, so much more negotiating goes on.A new turn begins with everyone rolling their die, moving, then choosing and revealing their action cards. When any merchant piece completes a lap around the board, the round ends and bonus points are awarded based on who has the majority in each gem color and who has completed a lap. After three rounds, the game is over and the highest score wins.Re-implemented by:     Edel, Stein & Reich',
        1998,
        10,
        25,
        25,
        14,
        6.75798, 
        'https://cf.geekdo-images.com/thumb/img/hBDymMYGWKQNbiuxDtqSQyYZDvQ=/fit-in/200x150/pic48605.jpg',
        'https://cf.geekdo-images.com/original/img/xFRII0rLyA7eb2CDF_GT4BS-eLE=/0x0/pic48605.jpg',
        'Negotiation',
        'Roll / Spin and Move, Set Collection, Simultaneous Action Selection'),
(
        15,
        'Cosmic Encounter',
        'By request of Fantasy Flight Games, Board Game Geek lists the various editions of Cosmic Encounter in separate entries. Each edition is the same game at its core, but the features, compatible expansions, and production differ among them. This entry is for the original 1977 Eon version.Players represent alien races that are seeking to spread themselves onto five foreign worlds.  To accomplish this, they make challenges against other players and enlist the aid of interested parties.  But alien powers, which are unique to each race, give players ways to bend or outright break some rule in the game.The game continues until one player occupies five planets in other systems to win. Shared victories are possible and a player need not occupy ones own system to win.',
        1977,
        12,
        90,
        90,
        15,
        6.91934, 
        'https://cf.geekdo-images.com/thumb/img/ku9JLe-4isTBgHyiJbZ5cSbf8S8=/fit-in/200x150/pic428608.jpg',
        'https://cf.geekdo-images.com/original/img/5koT3dPNbvckjXGwCFBX3TYfLLk=/0x0/pic428608.jpg',
        'Bluffing, Negotiation, Science Fiction',
        'Hand Management, Variable Player Powers'),
(
        16,
        'MarraCash',
        'Taking on the roles of shop owners in the Moroccan marketplace, players buy various shops, as color-coded tourists in the form of neat little wooden people in hats start showing up at the entry gate. Players can then move them into their own like-colored shops to earn money or move them into opponents shops for a share of the profits. After all the tourists have been placed onto the board, the player with the biggest bankroll takes the victory. This game combines some great auction elements with spatial relationships for an appealing overall effect.Contents:  1 game board  1 blue auction stone  1 counter sheet with:      - 24 shop signs (6 each of Ali, Anfa, Omar and Leila)      -   4 player aid cards24  plastic stands54 pawns = visitors (14 yellow, 10 each of red, blue, green and purple)25 game cards with souvenirsMoney in different values (500, 200, 100 and 25 Dirhams)',
        1996,
        12,
        60,
        60,
        16,
        6.82004, 
        'https://cf.geekdo-images.com/thumb/img/RkNqeFmjL2BD0fwtDbEGNmBJu0U=/fit-in/200x150/pic573942.jpg',
        'https://cf.geekdo-images.com/original/img/WxaZnaBbkRaqUW17Dzg0xyOBMd4=/0x0/pic573942.jpg',
        'Economic',
        'Auction/Bidding'),
(
        17,
        'Button Men',
        'This game gained a quick following after one of the major gaming conventions of 1999.  It features several characters, represented on actual stickpin buttons, that each have a unique allowance of polyhedral dice.  These dice endow each  character with fairly unique combat abilities.  Players roll the dice against each other and take their opponents dice as casualties.  The object of the game is take out the most die sides during the combat.  Its quite simple, quite inventive, and deeper than it would seem at first.',
        1999,
        10,
        5,
        5,
        17,
        6.35945, 
        'https://cf.geekdo-images.com/thumb/img/O2Vc-Gpw7Wqju1IgBlYTgTOWCAg=/fit-in/200x150/pic59279.jpg',
        'https://cf.geekdo-images.com/original/img/4NgPMx7BFX5LIrL-dLs_6MOsHd4=/0x0/pic59279.jpg',
        'Collectible Components, Dice, Fighting, Print & Play',
        'Dice Rolling, Push Your Luck'),
(
        18,
        'RoboRally',
        'The robots of the Robo Rally automobile factory spend their weekdays toiling at the assembly line. They put in hard hours building high-speed supercars they never get to see in action. But on Saturday nights, the factory becomes a world of mad machines and dangerous schemes as these robots engage in their own epic race.It takes speed, wits, and dirty tricks to become a racing legend! Each player chooses a robot and directs its moves by playing cards. Chaos ensues as all players reveal the cards theyve chosen. Players face obstacles like industrial lasers, gaping pits, and moving conveyor belts -- but those can also be used to their advantage! Each player aims to make it to each of the checkpoints in numerical order. The first player to reach all of the checkpoints wins. (source: http://avalonhill.wizards.com/games/robo-rally/comingsoon)In RoboRally players each control a different robot in a race through a dangerous factory floor. Several goals will be placed on the board and you must navigate your robot to them in a specific order. The boards can be combined in several different ways to accommodate different player counts and races can be as long or as short as players desire.In general, players will first fill all of their robots registers with facedown movement cards. This happens simultaneously and there is a time element involved. If you dont act fast enough you are forced to place cards randomly to fill the rest. Then, starting with the first register, everyone reveals their card. The card with the highest number moves first. After everyone resolves their movement they reveal the next card and so on. Examples of movement cards may be to turn 90 degrees left or right, move forward 2 spaces, or move backward 1 space though there are a bigger variety than that. You can plan a perfect route, but if another robot runs into you it can push you off course. This can be disastrous since you cant reprogram any cards to fix it!Robots fire lasers and factory elements resolve after each movement and robots may become damaged. If they take enough damage certain movement cards become fixed and can no longer be changed. If they take more they may be destroyed entirely. The first robot to claim all the goals in the correct order wins, though some may award points and play tournament style.The game was reprinted by Avalon Hill (Hasbro/WotC) in 2005.',
        1994,
        12,
        45,
        120,
        18,
        7.09744, 
        'https://cf.geekdo-images.com/thumb/img/4zQbF0XfyuNPaiv8rPLyFV-Sbl8=/fit-in/200x150/pic1000553.jpg',
        'https://cf.geekdo-images.com/original/img/6Qod68Kgmb6NgXWdOglFnfAZiiE=/0x0/pic1000553.jpg',
        'Maze, Miniatures, Racing, Science Fiction',
        'Action Queue, Grid Movement, Modular Board, Race, Simultaneous Action Selection'),
(
        19,
        'Wacky Wacky West',
        'A long time ago, in a village far, far away, some disturbed townsfolk decided to destroy their entire town in order to rid themselves of an evil menace (its technically a dog-mouse, but I think its an idiomatic thing).  Anyway, so the villagers rebuilt all the buildings in the town (including their precious outhouses), but forgot to include city walls, a river, or roads.  To rectify this, players lay tiles with one of these three things onto the board, and any building caught underneath them is automatically eliminated, except for outhouses.  When an outhouse would be destroyed, players take a vote on whether to place that particular section.  Each player is trying to retain the most of one type of building, and once all the pieces have been placed the winner is the person with the highest valued buildings still standing.Wacky, Wacky West re-make description:Fans of Klaus Teuber will be interested in this remake/redesign of Drunter und Dr&uuml;ber, a 1991 Spiel des Jahres winner.Just south of nowhere, theres the junction of the Mayfair & Rossdorf RR and the Turvy Trunk Line. Springing up from the desert like a tumbleweed lies the eccentric little town of Rossdorf. Like most western towns, Rossdorf has a Land Agent: Guy Dough, the brother of that wicked varmint Black Benny. A shrewd opportunist, Guys done sold all the town land (ceptin the outhouses) four times over! Every acre in town that aint got an outhouse on it is owned by the miners, the railroads, AND the fort captain. Just about a year ago, miners digging in the shadow of Fort Rossdorf struck the mother lode! But it wasnt gold, and it wasnt silver. No, my friend, it was just a little spring. Not any ordinary spring, though! It was a torrent of that mind-marbling drink the locals call Wacky Water! Now that waters done what the sun and the wind couldnt do: its made those landholders brave enough to take matters into their own hands. Now theyll use whatever means they can to bowl over the competition and lay claim to the only fertile spots left in town! Now the only thing stoppin em is the Town Charter Amendment #5, which states: no landholder may move, remove, or detonate any outhouse without a majority vote of the Town Citizens... Now one things for sure: somethings gonna stink in Rossdorf, purty darn soon.....In Wacky Wacky West you and your fellow townfolk place track tiles, street tiles, and river tiles hoping to destroy your rivals buildings. Every time someone tries to build over a precious outhouse, the town votes! You try to enlist your supporters (represented by cards) to vote with you to stop or encourage the play of certain tiles-perhaps saving some of your buildings or taking out those of your dastardly opponents.',
        1991,
        9,
        30,
        45,
        19,
        6.30282, 
        'https://cf.geekdo-images.com/thumb/img/ZbtiVO4RR4jwhiKJWcuifmT391Y=/fit-in/200x150/pic786075.jpg',
        'https://cf.geekdo-images.com/original/img/svmPt7Lb8Gs7ah8YzlSM2tqL9AU=/0x0/pic786075.jpg',
        'American West, Bluffing, City Building',
        'Tile Placement, Voting'),
(
        20,
        'Full Metal Planète',
        'In this game of science fiction strip mining, players land on a planet and try and grab as much ore as possible and take off before the game is over.  Each player has tanks, boats, barges, mining equipment and a base ship at his disposal and will have to contend with the weather and the other miners.  The game uses an action point allowance system and thus is dice free.  Each player on his turn has a pool of points that he can divide in a variety of ways, putting all the points into one units movement or dividing them among several units.  Each turn is timed so players have to think quickly, and once a move has been made it cannot be retracted.  The game itself is beautifully put together, with a detailed hex grid and real metal miniatures for all of the units.Online Play:     Full Metal Galaxy    Full Metal Program    VASSAL moduleRe-implemented by:    Full Metal ConquÃªte (as a two-player version)Expanded by:    Full Metal Planete: Plateau Modulaire.Microbadges: - Full Metal Plan&egrave;te fan  Buy It',
        1988,
        12,
        90,
        90,
        20,
        7.47469, 
        'https://cf.geekdo-images.com/thumb/img/RqZ6CwJEHShUwFtPI0a4OVSKJbA=/fit-in/200x150/pic451783.jpg',
        'https://cf.geekdo-images.com/original/img/RJJama3a9_wLenjvKJh58rgxlBE=/0x0/pic451783.jpg',
        'Science Fiction',
        'Action Points'),
(
        21,
        'Gateway to the Stars',
        'A 4X game (eXplore, eXpand, eXploit, eXterminate) along the lines of Stellar Conquest, players each control a space faring empire that moves out to other star systems to explore and conquer.',
        1994,
        12,
        0,
        0,
        21,
        5.5, 
        'https://cf.geekdo-images.com/thumb/img/Z3X2trAy--BjsYROFv8lpSqnPNs=/fit-in/200x150/pic1615146.jpg',
        'https://cf.geekdo-images.com/original/img/zhxcAlEmucfzLgJKSoxhPht-yOk=/0x0/pic1615146.jpg',
        'Civilization, Exploration, Science Fiction',
        ''),
(
        22,
        'Magic Realm',
        'From the 2nd edition rulebook intro for MAGIC REALM:MAGIC REALM is a game of fantasy adventuring, set in a land filled with monsters, fabulous treasures, great warriors, and magicians. The scene is set in the ruins of a mighty kingdom, now inhabited by sparse groups of natives and swarms of monsters. Beneath it all are the rich remnants of a magical civilization, scattered and lost across the map.To this scene come the adventurers, seekers of riches and fame, to make a name for themselves in this promising field. Swordsman and Dwarf, Magician and Sorceror, the humans and the half-humans come seeking to loot the legendary riches of a lost civilization. Now you can play the part of one of these adventurers, stepping into an unknown Realm of magic and monsters, battles and treasures.As a player, you will take on the role of one of the sixteen major characters who are represented in detail in the game. You will control where he goes, what he tries to do, how he handles himself in combat, and much more. In the course of the game, you will run into deadly monsters, tribes of humans ranging from old friends to sworn enemies, and treasures that will enhance your abilities in many ways.MAGIC REALM is a complex game designed to recapture the suspense and desperate struggles of fantasy literature. The game creates a small but complete fantasy world, where each game is a new adventure with a new map where everything lies hidden at new locations. The game includes many more playing pieces than are actually used in a single playing. The additional pieces are set up and can appear, depending on the directions in which the characters explore, but many of the treasure troves, treasures, and spells will still be set up, unfound, when the game ends, and many of the monsters and natives might never be met. The result is an extremely unpredictable game full of surprises, a game that plays very differently each time it is played.The complete game system includes hiking, hiding and searching, fatigue, wounds, rest, trade, hiring natives, and combat between characters, monsters, and natives using a variety of weapons on horseback and afoot, as well as many magical effects.Between exploring a new land where the mountains, caves, valleys, and woods change every game, and not knowing what you will find in each place, you will find each game a new and unpredictable adventure, filled with surprises. You will find this like no other board game you have ever played.Avalon Hill Complexity rating - 9See also the list of articles about Magic Realm in The General.',
        1979,
        12,
        240,
        240,
        22,
        7.17185, 
        'https://cf.geekdo-images.com/thumb/img/Lz-oN-BoiBvBrbZ9U94f8VrErnE=/fit-in/200x150/pic148345.jpg',
        'https://cf.geekdo-images.com/original/img/CeJiWNodJGwBPse17RA6p4krH6c=/0x0/pic148345.jpg',
        'Adventure, Exploration, Fantasy',
        'Action Queue, Modular Board, Role Playing, Simultaneous Action Selection, Variable Player Powers'),
(
        23,
        'Divine Right',
        'Classic game of fantasy empires clashing.  Each player controls a unique realm and attempts to use diplomacy and might to ascend to rulership.  A colorful map and a host of fantastic creatures bring out a fleshed out fantasy world.Expanded by:    Divine Right: Scarlet Empire',
        1979,
        12,
        360,
        360,
        23,
        7.06674, 
        'https://cf.geekdo-images.com/thumb/img/z3hoRRSkTpJYRnTY0l_NlCvuhSc=/fit-in/200x150/pic1440309.jpg',
        'https://cf.geekdo-images.com/original/img/xzG8v3IifCTkKcVi_AdvVlgXx50=/0x0/pic1440309.jpg',
        'Fantasy, Political, Wargame',
        'Dice Rolling, Hexagon Grid, Simulation, Variable Phase Order'),
(
        24,
        'Twilight Imperium',
        'Sprawling game of space faring races out to dominate known space.  This game combines a number of elements from other game systems into a unique package.  Hex tiles create the game board and each player begins with a race with unique powers.  The game focuses heavily on a political voting phase and a web of trade agreements between players.Part of the Twilight Imperium Series / Family.Expanded with:    Twilight Imperium: Borderlands    Twilight Imperium: Distant Suns    Twilight Imperium: Twilight Armada    Twilight Imperium: The Outer RimRe-implemented in:    Twilight Imperium (Second Edition)    Twilight Imperium (Third Edition)    Twilight Imperium (Fourth Edition)',
        1997,
        12,
        240,
        240,
        24,
        6.64903, 
        'https://cf.geekdo-images.com/thumb/img/5ub28oCmkGHYgt-d00RkEgX5AQU=/fit-in/200x150/pic857.jpg',
        'https://cf.geekdo-images.com/original/img/COM3xWJeoqoM5PXSwjRCjujM1cI=/0x0/pic857.jpg',
        'Civilization, Negotiation, Political, Science Fiction, Space Exploration, Wargame',
        'Dice Rolling, Hexagon Grid, Modular Board, Tile Placement, Variable Player Powers, Voting'),
(
        25,
        'Battlemist',
        'In this fantasy relative to Twilight Imperium, players control races that must juggle military and economic concerns with a quest to gather the magical stars spread across the land.  The game board is made up of hex tiles and players use a resource system that has similarities to The Settlers of Catan.  A card driven system resolves players quests.Expanded by:    Battlemist: The Sails of WarReimplemented by:    Runewars',
        1998,
        12,
        200,
        200,
        25,
        5.88905, 
        'https://cf.geekdo-images.com/thumb/img/V53yd2BGcK9Of-w0S7KQQoOzHQ0=/fit-in/200x150/pic4222282.jpg',
        'https://cf.geekdo-images.com/original/img/6iVcvIDZRlaDBjWhomct0tCp9xI=/0x0/pic4222282.jpg',
        'Exploration, Fantasy, Wargame',
        ''),
(
        26,
        'Age of Renaissance',
        'A game that is often described as a semi-sequel to Civilization.Players attempt to build up their cultures during the Middle Ages and Renaissance periods. The game features a card deck that holds events, payout cards, and famous leaders of the particular eras. Although all cards will turn up somewhere during the game, the timing and position in which they will be played is crucial and will ensure a different game every time.The main goal of each city-state is to gain points in the form of technical advances, while keeping their cultures misery level as low as possible. The payout structure is similar to those of Civilization and Advanced Civilization in that more resources of the same type yield increasingly higher payouts. This time particular payouts are triggered by card play for every player at once. An ingenious and very smooth working &ldquo;combat&rdquo; system is implemented to determine province &ndash; and thus resource - control.',
        1996,
        12,
        120,
        300,
        26,
        7.09914, 
        'https://cf.geekdo-images.com/thumb/img/X8XywCNXpWIi2aGIHAVw_BvVunA=/fit-in/200x150/pic87721.jpg',
        'https://cf.geekdo-images.com/original/img/Uvu0ANX4_XaHXOdtZ79gpz9VI8Q=/0x0/pic87721.jpg',
        'Civilization, Economic, Medieval, Renaissance',
        'Area Movement, Auction/Bidding'),
(
        27,
        'Supremacy',
        'Supremacy pits conventional superpowers against one another for control of the earth.  Along the lines of modern warfare Risk, only with an integrated supply/demand economic system.  Warfare comes in all forms from conventional, biological, chemical and all the way to nuclear.  Neat little plastic mushroom clouds are included to show where regions of the earth have been blasted, and if nuclear winter occurs, all players lose.  The game also spawned a great many supplements to expand the game further.',
        1984,
        12,
        340,
        340,
        27,
        5.61408, 
        'https://cf.geekdo-images.com/thumb/img/sQFZ4rqeQYTwF1R6V5MDv14ngY4=/fit-in/200x150/pic368339.jpg',
        'https://cf.geekdo-images.com/original/img/L2y35lLLXtoD_wWlmrq2ZMdLsIo=/0x0/pic368339.jpg',
        'Economic, Political, Wargame',
        'Commodity Speculation, Dice Rolling'),
(
        28,
        'Illuminati (Second Edition)',
        'In this classic Steve Jackson (I) game of world domination, each player is a secret society attempting to spread its tendrils into special interest groups throughout the world. This latest edition comes with additional cards and reworked graphics to bring the venerable game up to date.Re-issue of:    Illuminati (Small plastic box with 54 black and white cards and paper money)Expansions:    Illuminati: Y2K    Illuminati: Brainwash (re-work of Illuminati Expansion Set 3)    Illuminati: Bavarian Fire Drill    Illuminati: Mutual Assured DistractionSpin Off:    Illuminati: Crime Lords',
        1987,
        12,
        60,
        180,
        28,
        6.50802, 
        'https://cf.geekdo-images.com/thumb/img/5tVxbGMvGDvaYd8uVOeu-nPowt8=/fit-in/200x150/pic4206838.jpg',
        'https://cf.geekdo-images.com/original/img/Spqi-g9bDkzjrIcvMKmY8eRnsJc=/0x0/pic4206838.jpg',
        'Card Game, Humor, Negotiation, Political, Science Fiction',
        'Card Drafting, Dice Rolling, Network and Route Building, Tile Placement, Variable Player Powers'),
(
        29,
        'Terrain Vague',
        'Having many system similarities to Full Metal PlanÃ¨te, Terrain Vague is a war game-ish game based on young gangs of kids fighting over turf in a junk yard.  Imagine a R-rated Little Rascals movie with weapons and you get the idea.A winner of the 1992 Concours International de CrÃ©ateurs de Jeux de SociÃ©tÃ©.',
        1993,
        10,
        120,
        120,
        29,
        6.65662, 
        'https://cf.geekdo-images.com/thumb/img/0W6SBp_VIMyeoOzzWENTgJaPV5w=/fit-in/200x150/pic237984.jpg',
        'https://cf.geekdo-images.com/original/img/1OlwNEQTOtf29CqSuUooKJJI2HI=/0x0/pic237984.jpg',
        'Fighting, Humor',
        'Action Points, Modular Board'),
(
        30,
        'Dark Tower',
        'An epic fantasy quest to recover an ancient magic scepter from a tyrant king in his Dark Tower, brought to life in electronic form.To vanquish the usurper, players search the four realms of the circular game board for three keys to unlock the towers gate.  On this journey, there are battles to be fought against roving bands of brigands, dragons, plague and hunger.  There are bazaars to visit to purchase supplies and assistants for the quest.  There are uncharted territories to get lost in and tombs and ruins to plunder.  And there is a mighty army to be raised before the player can lay seige to the tower and fight either to glorious victory or crushing defeat.Dated and primitive by todays standards, Dark Tower was nevertheless an astonishing achievement when it was released in 1981.  Every aspect of the game was monitored by a small computer inside the black plastic shell of the tower itself, an unheard of innovation at the time.  Players input their moves on a small membrane keypad each turn and the computer took over from there, doing everything from conducting the progress of battles to keeping track of how much (or little) food was left to feed the players always hungry warriors.  It could even play recognizable pieces of music at significant points during the game.',
        1981,
        10,
        90,
        90,
        30,
        6.7298, 
        'https://cf.geekdo-images.com/thumb/img/H3ZnI3miTIjOHTqnHEaePt3C0ig=/fit-in/200x150/pic204975.jpg',
        'https://cf.geekdo-images.com/original/img/rlDTeYUHEmTPQiCR-Z51lTd0JFk=/0x0/pic204975.jpg',
        'Adventure, Electronic, Exploration, Fantasy, Fighting',
        'Area Movement, Push Your Luck'),
(
        31,
        'Dark World',
        'Along the lines of HeroQuest comes a much more heavily produced game called Dark World. One player is the evil lord who controls the dungeon in which the rest of the players move their characters from room to room, fighting monsters and gaining treasure. Real working treasure chests with magic weapons inside and the figures even get to put their new weapons in their characters hands.',
        1991,
        10,
        90,
        90,
        31,
        5.27036, 
        'https://cf.geekdo-images.com/thumb/img/iGJDAfuDrT40OIU7WU7FxKA_A4s=/fit-in/200x150/pic525738.jpg',
        'https://cf.geekdo-images.com/original/img/ILdFE-JACp1c0N1HgKGZPL8rmdU=/0x0/pic525738.jpg',
        'Adventure, Exploration, Fantasy, Fighting, Miniatures',
        'Dice Rolling, Grid Movement'),
(
        32,
        'Buffalo Chess',
        'In Buffalo Chess, a.k.a. Bison, one player represents Indians who are trying to keep the village from being overrun by buffalo. This player moves the Indian chief and his dogs while the other player takes charge of the herd of rampaging buffalo, all of which are represented by nice little wooden pieces. Each side has its own style of play as the pieces move differently.',
        1975,
        8,
        30,
        30,
        32,
        6.12531, 
        'https://cf.geekdo-images.com/thumb/img/GO6xPlP_uu7Mbul9-1uv7CUwCIU=/fit-in/200x150/pic4604213.jpg',
        'https://cf.geekdo-images.com/original/img/HfDcUODgpHiTpcgg-XbaK96T4pg=/0x0/pic4604213.jpg',
        'Abstract Strategy, American West',
        '');
